// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1xa-WZ_Rmo3MI7eaAUxBKEMDwYkhfRiQ',
    appId: '1:547590045444:web:6a645877780f981d81da51',
    messagingSenderId: '547590045444',
    projectId: 'janma-schotter',
    authDomain: 'janma-schotter.firebaseapp.com',
    storageBucket: 'janma-schotter.appspot.com',
    measurementId: 'G-DZB01X6853',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRg4Gn6S5HrTAbmwSJB_WBPFRRm0JGAQA',
    appId: '1:547590045444:android:c2d37c98328418d681da51',
    messagingSenderId: '547590045444',
    projectId: 'janma-schotter',
    storageBucket: 'janma-schotter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk4LY0bt65J4JZNWTv_997H3p_TIcPoIk',
    appId: '1:547590045444:ios:df413ce76ba8cb4081da51',
    messagingSenderId: '547590045444',
    projectId: 'janma-schotter',
    storageBucket: 'janma-schotter.appspot.com',
    androidClientId: '547590045444-20f0sjpevauhvmqs5ivi4u92ag9vf6vt.apps.googleusercontent.com',
    iosClientId: '547590045444-5tfmm0r7rkqo9o9jbodoaqu85beci91l.apps.googleusercontent.com',
    iosBundleId: 'com.example.janmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk4LY0bt65J4JZNWTv_997H3p_TIcPoIk',
    appId: '1:547590045444:ios:9a0830eb4b3a37af81da51',
    messagingSenderId: '547590045444',
    projectId: 'janma-schotter',
    storageBucket: 'janma-schotter.appspot.com',
    androidClientId: '547590045444-20f0sjpevauhvmqs5ivi4u92ag9vf6vt.apps.googleusercontent.com',
    iosClientId: '547590045444-ng48auq5k64pn7qkln629uco49lqcsgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.janmanager.RunnerTests',
  );
}
